### ISSUE TITLE
I am missing the "view more" link

### ISSUE THREAD

**Issue by grafst** [danilopolani/filament-plausible-widget#7]
![SCR-20240316-isyv](https://github.com/danilopolani/filament-plausible-widget/assets/8471055/dd4ffdc5-9916-4d7e-ba3a-89769324adbd)

**Comment by danilopolani** [comment]
Hey!
Thank you for the issue. What version of the package are you using?

**Comment by grafst** [comment]
v3.0.0

**Comment by danilopolani** [comment]
Since the package is now using the native Filament widgets, we can't put any more links in the footer as previously.
Now you will find the "View more" link under the heading.  

Fixed in v3.1.0

<img width="567" alt="image" src="https://github.com/danilopolani/filament-plausible-widget/assets/6277291/309a6f42-35c5-47ac-9742-4604e2b6c1a3">

**Comment by grafst** [comment]
great! :)
however plausible.io is hardcoded, but it should respect the FILAMENT_PLAUSIBLE_HOST config entry.
I can make a pull request if you want...

**Comment by danilopolani** [comment]
@grafst you're right, sorry! Yeah a PR would be awesome, thank you :)
